### ISSUE TITLE
twshoot error, unable to crop tweet screenshot

### ISSUE THREAD

**Issue by thruthfulas** [travisbrown/cancel-culture#35]
twshoot panicks and is unable to generate a cropped screenshot (normal invocation with default width). The -full screenshot is created though.

`$ twshoot -n https://twitter.com/POTUS/status/1445020443744870401`
> thread 'main' panicked at 'Image index (2147483649, 1) out of bounds (800, 868)', /Users/truth/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/buffer.rs:724:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

From the index value it seems some kind of integer overflow issue ?   
Output with RUST_BACKTRACE=full:
> thread 'main' panicked at 'Image index (2147483649, 1) out of bounds (800, 868)', /Users/truth/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/buffer.rs:724:21
stack backtrace:
   0:        0x1027b0aae - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0b3cb0f81eb6c032
   1:        0x1027e4c7c - core::fmt::write::h01b240c0519e8c85
   2:        0x1027aa22a - std::io::Write::write_fmt::h146f386a5b35d587
   3:        0x1027aab0f - std::panicking::default_hook::{{closure}}::h5f8b7ffe7769db61
   4:        0x1027aa69f - std::panicking::default_hook::h9f87fc2fdf4f1125
   5:        0x1027ab1d2 - std::panicking::rust_panic_with_hook::h32f3432eccbbcf03
   6:        0x1027b0f05 - std::panicking::begin_panic_handler::{{closure}}::heec496a5329a15c8
   7:        0x1027b0c28 - std::sys_common::backtrace::__rust_end_short_backtrace::h9ba91ee04b4386bb
   8:        0x1027aac13 - _rust_begin_unwind
   9:        0x1027f8b1b - std::panicking::begin_panic_fmt::ha031f2819d16b9cf
  10:        0x102472363 - cancel_culture::browser::twitter::crop_tweet::hac6ca890e72c3cf9
  11:        0x102445eac - twshoot::main::{{closure}}::h1b16770947b6e6e6
  12:        0x102484074 - std::thread::local::LocalKey<T>::with::h4edb7557c6e05cb1
  13:        0x102431ff8 - tokio::macros::scoped_tls::ScopedKey<T>::set::hdd7df53fc2e3a808
  14:        0x102436c75 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1e92500ec3c79581
  15:        0x102431364 - tokio::park::thread::CachedParkThread::block_on::hdd3ab10236246b71
  16:        0x1023bb92e - tokio::runtime::thread_pool::ThreadPool::block_on::h8a650a04a08a1c63
  17:        0x102481b13 - tokio::runtime::Runtime::block_on::h8ffafbc8ba2d79b3
  18:        0x1023fd34b - twshoot::main::heb5f03a1b718e143
  19:        0x10242331a - std::sys_common::backtrace::__rust_begin_short_backtrace::h38463d8620859ad9
  20:        0x102476fe1 - std::rt::lang_start::{{closure}}::h57dfe0db54bea119
  21:        0x1027ae055 - std::rt::lang_start_internal::h6f56f13a742d6e93
  22:        0x1023fd4e9 - _main
  
So supposedly it happens in this line https://github.com/travisbrown/cancel-culture/blob/cfc7ee54be100bf511a5485706773e9b8d50973d/src/bin/twshoot.rs#L52
  Run on macOS with ChromeDriver using Chrome 64, rustc version 1.55.0

**Comment by travisbrown** [comment]
Thanks for reporting this, and for all the information! I haven't had a chance to take a closer look yet, but I have a guess about what it could be, and will let you know when it's fixed.

**Comment by travisbrown** [comment]
It took many months but I think this should be fixed in #59.
