### ISSUE TITLE
Error on running deleted-tweets

### ISSUE THREAD

**Issue by mtae** [travisbrown/cancel-culture#54]
> Error: an error occurred when piloting the wayback machine subcrate:
> ClientError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })

Getting this error whenever I try to run the deleted-tweets report (on windows if that's relevant)

**Comment by travisbrown** [comment]
This looks like a JSON parsing error that would result from the Wayback Machine CDX server sending something unexpected.

If you try `https://web.archive.org/cdx/search/cdx?url=twitter.com/<USERNAME>&output=json` in a browser (changing `<USERNAME>` as needed), do you get valid JSON?

**Comment by mtae** [comment]
Interesting I get this message when I tried with the username 'TaylorLorenz' (the journalist) but it works with my username.

`org.archive.util.io.RuntimeIOException: org.archive.wayback.exception.AdministrativeAccessControlException: Blocked Site Error`

**Comment by Mennaruuk** [comment]
> Interesting I get this message when I tried with the username 'TaylorLorenz' (the journalist) but it works with my username.
> 
> `org.archive.util.io.RuntimeIOException: org.archive.wayback.exception.AdministrativeAccessControlException: Blocked Site Error`

That’s because presumably Lorenz asked the Wayback Machine to exclude her profile, probably because she has faced multiple waves of harassment.

**Comment by travisbrown** [comment]
Tracked in #55.
